import numpy as np
import time

# ==========================================
# QUANTUM ENTROPY AUDITOR (BASELINE)
# ==========================================
def run_baseline_audit(filepath):
    """
    Loads a raw binary quantum bitstream and calculates the foundational 
    cryptographic metrics: Bias, Shannon Entropy, and Autocorrelation.
    """
    print(f"\n=== QUANTUM ENTROPY AUDITOR ===")
    print(f"-> Target File: {filepath}")
    
    start_time = time.time()
    
    try:
        # 1. Load the compressed binary file directly into a NumPy array
        # dtype=np.uint8 ensures we read exactly 1 physical Byte (8 bits) at a time
        print("-> Loading binary stream from disk...")
        raw_bytes = np.fromfile(filepath, dtype=np.uint8)
    except FileNotFoundError:
        print(f"[ERROR] Could not find {filepath}. Did you run the digitalization script?")
        return

    # 2. Explode the Bytes back into individual bits
    # Example: the byte '170' becomes the array [1, 0, 1, 0, 1, 0, 1, 0]
    print("-> Unpacking bytes into raw bit array...")
    bitstream = np.unpackbits(raw_bytes)
    
    total_bits = len(bitstream)
    print(f"-> Total Bits Extracted: {total_bits:,}")
    
    if total_bits == 0:
        print("[ERROR] Bitstream is empty.")
        return

    print("\n=== CALCULATING METRICS ===")
    
    # 3. Calculate Bias (Ratio of 1s)
    # Since the array only contains 0s and 1s, the mean is exactly the probability of getting a 1
    p_1 = np.mean(bitstream)
    p_0 = 1.0 - p_1
    print(f"-> P(1) [Ratio of 1s]: {p_1:.6f} (Ideal: 0.500000)")
    print(f"-> P(0) [Ratio of 0s]: {p_0:.6f} (Ideal: 0.500000)")
    
    # 4. Calculate Shannon Entropy (H)
    # Using a tiny epsilon to prevent log2(0) crashes if the stream is totally broken
    epsilon = 1e-15
    p_0_safe = max(p_0, epsilon)
    p_1_safe = max(p_1, epsilon)
    
    shannon_entropy = -(p_0_safe * np.log2(p_0_safe)) - (p_1_safe * np.log2(p_1_safe))
    print(f"-> Shannon Entropy (H): {shannon_entropy:.8f} bits/bit (Ideal: 1.00000000)")

    # 5. Calculate First-Order Autocorrelation (Serial Correlation)
    # We compare the array to itself, shifted by 1 position
    print("-> Calculating First-Order Autocorrelation (this may take a few seconds)...")
    
    # Slice the arrays to align them:
    # x_current: Bit 0 to N-1
    # x_next:    Bit 1 to N
    x_current = bitstream[:-1]
    x_next = bitstream[1:]
    
    # Calculate the Pearson correlation matrix and extract the coefficient
    correlation_matrix = np.corrcoef(x_current, x_next)
    autocorrelation = correlation_matrix[0, 1]
    
    print(f"-> Autocorrelation Coefficient: {autocorrelation:.6f} (Ideal: 0.000000)")

    elapsed_time = time.time() - start_time
    print(f"\n-> Audit completed in {elapsed_time:.2f} seconds.")

# ==========================================
# MAIN EXECUTION BLOCK
# ==========================================
if __name__ == "__main__":
    # Ensure this points to the exact file generated by digitalization.py
    TARGET_BITSTREAM = "whitened_quantum_keys.bin"
    
    run_baseline_audit(TARGET_BITSTREAM)